name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env: # Definição das variáveis de ambiente
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and start containers
        run: docker-compose up -d
        working-directory: ./backend  # Diretório do docker-compose.yml

      - name: Run Container
        run: docker-compose exec app bash
        working-directory: ./backend

      - name: Composer Install
          run: composer install
          working-directory: ./backend

      - name: Run Migrations
          run: php artisan migrate
          working-directory: ./backend

      - name: Run Tests
          run: ./vendor/bin/phpunit
          working-directory: ./backend

      - name: Stop containers
        run: docker-compose down
        working-directory: ./backend  # Diretório do docker-compose.yml
