name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env: # Definição das variáveis de ambiente
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and start containers
        run: docker-compose up -d
        working-directory: ./backend  # Diretório do docker-compose.yml

      - name: Wait for services to start
        run: sleep 20  # Ajuste esse valor conforme necessário para dar tempo aos serviços para iniciar.

      - name: Run Composer Install
        run: docker-compose exec -T app composer install
        working-directory: ./backend

      - name: Run Migrations
        run: docker-compose exec -T app php artisan migrate
        working-directory: ./backend

      - name: Run Tests
        run: docker-compose exec -T app ./vendor/bin/phpunit
        working-directory: ./backend

      - name: Stop containers
        run: docker-compose down
        working-directory: ./backend  # Diretório do docker-compose.yml
