name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env: # Definição das variáveis de ambiente
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and start containers
        run: docker-compose up -d
        working-directory: ./backend

      - name: Configurar permissões para Composer e Artisan
        run: |
          sudo useradd -G www-data,root -u $uid -d /home/$user $user
          sudo mkdir -p /home/$user/.composer &&
          sudo chown -R $user:$user /home/$user
        shell: bash

      - name: Alterar permissões do arquivo composer.lock
        run: |
          sudo chown $user:$user ./backend/composer.lock
        working-directory: ./backend

      - name: Executar docker-compose
        run: |
          sudo docker-compose exec -T app composer update
        working-directory: ./backend

      - name: Run Composer Install
        run: sudo docker-compose exec -T app composer update
        working-directory: ./backend

      - name: Run Migrations
        run: sudo docker-compose exec -T app php artisan migrate
        working-directory: ./backend

      - name: Run Tests
        run: sudo docker-compose exec -T app ./vendor/bin/phpunit
        working-directory: ./backend

      - name: Stop containers
        run: docker-compose down
        working-directory: ./backend  # Diretório do docker-compose.yml
