name: CI-CD
on:
  push:
    branches: main
env: # Definição das variáveis de ambiente
  DB_CONNECTION: mysql
  DB_HOST: http://0.0.0.0
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root
jobs:
  test-php: #rodar testes unitarios e instalar as lib com o composer
    name: Test PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1 # Use your PHP version
          extensions: mbstring, bcmath # Setup any required extensions for tests
      - name: Composer install
        run: composer install
        working-directory: ./backend
      - name: Up DataBase
        run: docker-compose up -d db
        working-directory: ./backend
      - name: Run Migrations
        run: php artisan migrate --force
        working-directory: ./backend
      - name: Run Tests
        run: ./vendor/bin/phpunit
        working-directory: ./backend