name: CI-CD
on:
  push:
    branches: main
jobs:
  test-php: #rodar testes unitarios e instalar as lib com o composer
    name: Test PHP
    runs-on: ubuntu-latest
    env: # Definição das variáveis de ambiente
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 8.1 # Use your PHP version
          extensions: mbstring, bcmath # Setup any required extensions for tests
      - name: Composer install
        run: composer install
        working-directory: ./backend
      - name: Up DataBase
        run: docker-compose up -d db
        working-directory: ./backend
      - name: Run Tests
        run: ./vendor/bin/phpunit
        working-directory: ./backend